version: "3.9"
services:
  web:
    restart: always
    build: ./
    volumes:
      - ./:/app
    env_file:
      - shop/.env
    ports:
      - 8000:8000
    command: >
      sh -c "python manage.py makemigrations &&
      python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - db
  db:
    image: postgres:14
    env_file:
      - shop/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/



  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    
  worker:
    restart: always
    build: .
    volumes:
      - ./:/app


    depends_on:
      - redis
      - web
      - db
    command: celery -A shop worker -l info


  celery-beat:
    restart: always
    build: .
    volumes:
      - ./:/app
    depends_on:
      - redis
      - db
      - web
      - worker
    command: celery -A shop beat -l info
volumes:
  postgres_data:
